//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medic
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int Id_supplier { get; set; }
        public string Full_name_supplier { get; set; }
        public string Email_supplier { get; set; }
        public string Tele_supplier { get; set; }
        public string Address_supplier { get; set; }
        public string Region_supplier { get; set; }
    }
}
